class VMError(Exception): ...
class InvalidSelection(VMError): ...
class OutOfStock(VMError): ...
class InsufficientFunds(VMError): ...
class CannotMakeChange(VMError): ...
class NotInRightState(VMError): ...
